In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.read_csv('homeprices2.csv')

In [4]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [15]:
 import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [17]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [25]:
Target = df.price
input = df.drop(['price'], axis='columns')

In [26]:
input.head()

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8

In [27]:
reg = linear_model.LinearRegression()
reg.fit(input, Target)

LinearRegression()

In [33]:
reg.predict([[2600, 3.0, 20]])

array([518217.63297611])

In [31]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [34]:
 reg.predict([[3000,3,40]])

array([498408.25158031])